site_name: JW Platform Developer Guide
theme: readthedocs
repo_url: https://github.com/jwplayer/jwplatform-docs
site_favicon: http://www.jwplayer.com/wp-content/themes/jwplayer-20/assets/images/favicon.ico
markdown_extensions:
- markdown.extensions.toc:
title: "THIS IS A CUSTOM TOC"
pages:
- Introduction: 'index.md'
# - Taking Advantage of the Platform API: 'taking_advantage.md'
# - Embed Players with the Platform API: 'embed_players.md'
# - Batch Video Migration with the Platform API: 'batch_migration.md'
- Release Notes: 'release-notes.md'