site_name: JW Platform Developer Guide
theme: jwplayer
site_dir: developer-guide
repo_url: https://github.com/jwplayer/jwplatform-docs
site_favicon: http://www.jwplayer.com/wp-content/themes/jwplayer-20/assets/images/favicon.ico
pages:
    - Introduction: 'index.md'
    - Release Notes: 'release-notes.md'
