site_name: JW Platform Developer Guide
theme: jwplayer
extra:
  product: platform
site_dir: developer-guide
repo_url: https://github.com/jwplayer/jwplatform-docs
site_favicon: http://www.jwplayer.com/wp-content/themes/jwplayer-20/assets/images/favicon.ico
pages:
    - Introduction: 'index.md'
    - Building Your Site:
      - Embedding Players: 'building_your_site/embedding_players.md'
      - Feeds Widgets: 'building_your_site/widgets/feeds_widgets.md'
      - Feeds Widget CSS Reference: 'building_your_site/widgets/feeds_widget_css_reference.md'
    - Cross Platform Distribution:
      - JW Showcase for Web: 'jw_showcase/web/jw_showcase_for_web.md'
      - Jw Showcase for Apple TV: 'jw_showcase/apple_tv/jw_showcase_for_apple_tv.md'
    - Integrating with your CMS:
      - Uploading Videos: 'integrating_with_your_cms/uploading_videos.md'
      - Batch Migrations: 'integrating_with_your_cms/batch_migration.md'
    - Release Notes: 'release-notes.md'
