site_name: JW Platform Developer Guide
theme:
  name: null
  custom_dir: node_modules/mkdocs-jwplayer/jwplayer
  include_search_page: true
  search_index_only: false
extra:
  product: platform
site_dir: developer-guide
repo_url: https://github.com/jwplayer/jwplatform-docs
nav:
    - Introduction: 'index.md'
    - Delivery API:
      - Overview: 'delivery-api/index.md'
      - Embedding Players: 'delivery-api/embedding-players.md'
      - Source Selection: 'delivery-api/sources.md'
      - URL Token Signing: 'delivery-api/url-token-signing.md'
      - Legacy Token Signing: 'delivery-api/legacy-url-token-signing.md'
    - Management API:
      - Overview: 'management-api/index.md'
      - Uploading Videos: 'management-api/uploading-videos.md'
      - Batch Migrations: 'management-api/batch-migration.md'
    - Analytics:
      - Analytics: 'management-api/analytics.md'
      - Overview: 'analytics-api/index.md'
      - Run a report: 'analytics-api/run-a-report.md'
      - Example report queries: 'analytics-api/example-report-queries.md'
      - Run a report with query tools: 'analytics-api/run-a-report-with-tools.md'
      - Analytics API reference: 'analytics-api/api-reference.md'
      - Metrics and dimensions: 'analytics-api/metrics-and-dimensions.md'
    - Advertising:
      - Advertising: 'management-api/advertising.md'
    - JW Showcase:
      - JW Showcase for Web: 'jw-showcase/web/jw-showcase-for-web.md'
    - Release Notes: 'release-notes.md'
markdown_extensions:
   - markdown_fenced_code_tabs
