site_name: JW Platform Developer Guide
theme: jwplayer
extra:
  product: platform
site_dir: developer-guide
repo_url: https://github.com/jwplayer/jwplatform-docs
site_favicon: http://www.jwplayer.com/wp-content/themes/jwplayer-20/assets/images/favicon.ico
pages:
    - Introduction: 'index.md'
    - Delivery API:
      - Overview: 'delivery-api/index.md'
      - Embedding Players: 'delivery-api/embedding-players.md'
      - Source Selection: 'delivery-api/sources.md'
      - URL Token Signing: 'delivery-api/url-token-signing.md'
      - Legacy Token Signing: 'delivery-api/legacy-url-token-signing.md'
    - Management API:
      - Overview: 'management-api/index.md'
      - Uploading Videos: 'management-api/uploading-videos.md'
      - Batch Migrations: 'management-api/batch-migration.md'
      - Analytics: 'management-api/analytics.md'
      - Advertising: 'management-api/advertising.md'
    - JW Showcase:
      - JW Showcase for Web: 'jw-showcase/web/jw-showcase-for-web.md'
    - Release Notes: 'release-notes.md'
markdown_extensions:
   - markdown_fenced_code_tabs
