site_name: JW Platform Developer Guide
theme: jwplayer
extra:
  product: platform
site_dir: developer-guide
repo_url: https://github.com/jwplayer/jwplatform-docs
site_favicon: http://www.jwplayer.com/wp-content/themes/jwplayer-20/assets/images/favicon.ico
pages:
    - Introduction: 'index.md'
    - Building Your Site:
      - Embedding Players: 'building-your-site/embedding-players.md'
      - Feeds Widgets: 'building-your-site/widgets/feeds-widgets.md'
      - Feeds Widget CSS Reference: 'building-your-site/widgets/feeds-widget-css-reference.md'
    - Cross-Platform Distribution:
      - JW Showcase for Web: 'jw-showcase/web/jw-showcase-for-web.md'
      - JW Showcase for Apple TV: 'jw-showcase/apple-tv/jw-showcase-for-apple-tv.md'
    - Integrating with your CMS:
      - Uploading Videos: 'integrating-with-your-cms/uploading-videos.md'
      - Batch Migrations: 'integrating-with-your-cms/batch-migration.md'
    - Release Notes: 'release-notes.md'
